### ISSUE TITLE
Bonus Code remains applied for all users on a machine 

### ISSUE THREAD

**Issue by vpopa22** [VISIT-X/vxpay-js#49] opened 2019-09-26 09:16 UTC
> Please describe the issue in as many details as possible.
Hi,
When you activate the bonus code modal : openSignUp(...showSignupCode: true) the specific bonus will remain active for all future users on the machine, not just the current(newly created user).
Even if the new account is not created(you just close the signup form without creating the new user), the bonus remains active(gets applied automatically) for any user that logs in after.

Same happens if you apply a voucher for a user, all users on the respective machine will benefit from the offer.

## Versions:
- `npm -v`:  5.8.0
- `node -v`: 8.11.4
- `vxpay-js`: 2.6.3

* you can find the last one by running `npm list vxpay-js --depth=0`

## Problem
Bonus code / Vouchers should only be applied for the current user, not every user on the machine.
Even if the new account is not created(you just close the signup form without creating the new user), the bonus remains active(gets applied automatically) for any user that logs in after.

## Details....
Found the issue on lucycat.com.

## Possible solutions
Vouchers/ Bonus Codes should be user specific, not machine specific.

Vlad@vxpages team

Thx !

**Comment by t1gor** [comment] 2020-01-22 09:06
@maddockman is that intended behaviour? We don't store the codes anywhere in the lib.

**Comment by maddockman** [comment] 2020-02-06 13:11
If the VXPay UI is still active in the DOM on VXPages, it keeps it's state as long as it is not removed from DOM.

Otherwise, the bonus codes are also stored in the backend session. So when the VXPay is called with the same session cookie, than the bonus code can still be restored from the session.

That means, it works as implemented but we could change the behaviour here for the reasons mentioned above in the issue description.

**Comment by t1gor** [comment] 2020-02-06 13:25
> If the VXPay UI is still active in the DOM on VXPages, it keeps it's state as long as it is not removed from DOM.

Well, this **was** intentional, but it seems that requires a change now :( Thanks for clarifications, will take a look.

**Comment by t1gor** [comment] 2022-02-17 06:23
@maddockman would that require changes from your side? Or is it only on the lib side?

**Comment by maddockman** [comment] 2022-02-18 07:12
Hi Igor, 

it should be solved in the UI, not the lib, we can close this here. I'll take care of the UI part :)

Thx, you're out now!

**Closed** 2022-02-18 07:16 UTC
Labels: bug
